#!/usr/bin/env bash
# Adapted from: https://github.com/davecheney/golang-crosscompile

set -e

PLATFORMS="darwin/386 darwin/amd64 freebsd/386 freebsd/amd64 freebsd/arm linux/386 linux/amd64 linux/arm windows/386 windows/amd64"

eval "$(go env)"

function go-alias {
  GOOS=${1%/*}
  GOARCH=${1#*/}
  eval "function go-${GOOS}-${GOARCH} { (CGO_ENABLED=0 GOOS=${GOOS} GOARCH=${GOARCH} go \$@ ) }"
}

for PLATFORM in $PLATFORMS; do
  go-alias $PLATFORM
done

mkdir -p bin

cd src

for PLATFORM in ${PLATFORMS}; do
    GOOS=${PLATFORM%/*}
    GOARCH=${PLATFORM#*/}
    CMD="go-${GOOS}-${GOARCH} build"
    echo "$CMD"
    $CMD
    if [ -x src ]; then mv src ../bin/fondu-$GOOS-$GOARCH; fi
    if [ -x src.exe ]; then mv src.exe ../bin/fondu-$GOOS-$GOARCH; fi
done

unset -f go-alias
