#!/usr/bin/env bash
# Adapted from: https://github.com/davecheney/golang-crosscompile

PLATFORMS="darwin/386 darwin/amd64 freebsd/386 freebsd/amd64 freebsd/arm linux/386 linux/amd64 linux/arm windows/386 windows/amd64"

eval "$(go env)"

function go-alias {
  GOOS=${1%/*}
  GOARCH=${1#*/}
  eval "function go-${GOOS}-${GOARCH} { (CGO_ENABLED=0 GOOS=${GOOS} GOARCH=${GOARCH} go \$@ ) }"
}

for PLATFORM in $PLATFORMS; do
  go-alias $PLATFORM
done

mkdir -p bin
for PLATFORM in ${PLATFORMS}; do
    mkdir -p bin/${PLATFORM}
    GOOS=${PLATFORM%/*}
    GOARCH=${PLATFORM#*/}
    CMD="go-${GOOS}-${GOARCH} build"
    echo "$CMD"
    $CMD
    if [ -x fondu ]; then mv fondu bin/$PLATFORM; fi
    if [ -x fondu.exe ]; then mv fondu.exe bin/$PLATFORM; fi
done

unset -f go-alias
